### ISSUE TITLE
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown

### ISSUE THREAD

**Issue by kiy4h** [tchx84/sugarapp#4]
I was trying to flatpak the sugarchess activity on Sugar Live Build.
(https://github.com/Kiy4h/sugarchess/tree/flatpak)

Following the tutorial from https://github.com/tchx84/sugarapp/blob/master/flatpak-guide.md#porting-an-application-with-sugarapp, I was stuck on the 4th step. Running the following:
```
$ SUGAR_BUNDLE_ID=org.sugarlabs.GNUChessActivity SUGAR_BUNDLE_PATH=$PWD sugarapp
```
prints out
```
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

Was it just me who did it wrong? Here's what's inside activity.info:
```
[Activity]
name = SimpleGNUChess
activity_version = 17
license = GPLv3
bundle_id = org.sugarlabs.GNUChessActivity
exec = sugar-activity3 GNUChessActivity.GNUChessActivity
icon = activity-gnuchess
show_launcher = yes
mime_types = application/x-chess-pgn;text/plain
summary = a Sugar interface to the gnuchess program
repository = https://github.com/walterbender/sugarchess
```

**Comment by tchx84** [comment]
Can you double check you ran `flatpak run` with `--socket=session-bus` ? also, did you get to remove the references to `activity.Activity`?

Also double check you got no direct calls to the `datastore`.
