### ISSUE TITLE
 Activity needs license metadata for AppStream file and question rgarding publishing of flatpak package

### ISSUE THREAD

**Issue by prakashujjwal1010** [tchx84/sugarapp#6]
when i was building and putting the app in repo using `flatpak-builder --force-clean --repo=repo  build org.sugarlabs.falabracmanActivity.json`

i am getting 
`[ERROR] Activity needs license metadata for AppStream file`
`Error: module falabracman-activity: Child process exited with code 255`

also,
do i have to publish the flatpak package of activity in flathub  by myself or sugarlabs will publish it?

**Comment by prakashujjwal1010** [comment]
the above error was solved as the activity.info was missing `license` tag :).
I have ported a falabracman activity [here](https://github.com/prakashujjwal1010/org.sugarlabs.falabracmanActivityl), : )

**Comment by quozl** [comment]
I see you have fixed it in https://github.com/prakashujjwal1010/org.sugarlabs.falabracmanActivity/blob/master/falabracman-info.patch but please fix it properly upstream in https://github.com/sugarlabs/falabracman-activity.

**Comment by prakashujjwal1010** [comment]
Okay, I have made a PR [here](https://github.com/sugarlabs/falabracman-activity/pull/12)

**Comment by tchx84** [comment]
Sorry for months delay, I am having issues with my github notifications.

You can first send a PR to https://github.com/tchx84/flathub, so I can help you get it right and then I can summit to falhub (you commits will be untouched, of course).
